const SET_SEARCH_TERM = 'SET_SEARCH_TERM'
const FETCH_BOOKS_PENDING = 'FETCH_BOOKS_PENDING'
const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS'
const FETCH_BOOKS_FAILED = 'FETCH_BOOKS_FAILED'

export { SET_SEARCH_TERM, FETCH_BOOKS_PENDING, FETCH_BOOKS_SUCCESS, FETCH_BOOKS_FAILED }
